version: '3'
services: 


  resizer:
    image: my-nginx
    build: .
    container_name: resizer
    ports:
      - "80:80"
    volumes:
      #  Место для хранения изображений
      - ./uploads:/uploads

      # Модуль обработки изображений не загружен по умолчанию. Делаем это вручную. 
      - ./configs/image-resizer-nginx.conf:/etc/nginx/nginx.conf
      
      # Файл конфигурации nginx, для ресайза и кэширования
      - ./configs/image-resizer-default.conf:/etc/nginx/conf.d/default.conf
      
      # Кэш. Можно закомментировать
      - ./cache/:/cache/
    
    
