version: '3'
services: 


  image-resizer:
    image: rgru/image-resizer:latest
    container_name: image-resizer
    ports:
      - "5080:80"
    volumes:
      #  Место для хранения изображений
      - ./images:/images

    
