FROM ubuntu:18.04
#FROM debian:stable-slim
LABEL maintainer="RGRU <ivlev@rg.ru>"

RUN apt-get -y update && apt-get -y install sshpass 

COPY configs  /app/configs
COPY migrations  /app/migrations
COPY templates  /app/templates
COPY docs  /app/docs

COPY image-resizer  /app/image-resizer

EXPOSE 7700

CMD bash -c "cd /app && ./image-resizer -serve 7700 -env=docker"




