version: '2.0'
services: 


  image-resizer-prod:
    image: image-resizer-prod
    container_name: image-resizer-prod
    ports:
      - "5080:80"
    volumes:
      #  Место для хранения изображений
      - ./../uploaded-files:/images

      # Модуль обработки изображений не загружен по умолчанию. Делаем это вручную. 
      - ./configs/image-resizer-nginx.conf:/etc/nginx/nginx.conf
      
      # Файл конфигурации nginx, для ресайза и кэширования
      - ./configs/image-resizer-default.conf:/etc/nginx/conf.d/default.conf
      
      # Кэш. Можно закомментировать. но тогда кэш будет исчезать при перезапуске контейнеров
      - ./../resized-images-cache/:/cache/
    
    
